### ISSUE TITLE
Update `negbin_solver` to `nbinom_lower_trunc_solver`

### ISSUE THREAD

**Issue by ethanwhite** [LennonLab/MicrobialBiodiversityTheory#123]
I received a bug report from a user trying to run your code and getting an error from https://github.com/weecology/macroecotools.

> when I run 'python runAnalysis.py -f F1' in both python 2.7 and 3.7, I got error "ImportError: cannot import name negbin_solver from macroeco_distributions". And I also cannot find "negbin_solver" in module "macroeco_distributions".

I helped them fix the issue, which resulted from a name change of the associated function in 2016. The new name is `nbinom_lower_trunc_solver`. You may want to consider updating your function calls if you want folks to be able to execute without running into issues.

**Comment by wrshoemaker** [comment]
Thanks for helping the user out and for the advice, Ethan! 

The function call is updated. I'm glad to hear that people are still interested in our code and analysis.

**Comment by ethanwhite** [comment]
My pleasure. Definitely exciting to see other folks working with your stuff.

Looks like there might be one more spot to change:
https://github.com/LennonLab/MicrobialBiodiversityTheory/blob/master/Python/modelsAndMetrics.py#L355

**Comment by wrshoemaker** [comment]
Ah yes 😳thank you.
